require 'yaml'
require 'hash_deep_merge'
require 'fileutils'
require 'logger'
require 'selenium-webdriver'

require_relative 'models/deployment'
require_relative 'models/user_role'
require_relative 'models/user'

require_relative 'config/config'
require_relative 'config/config_bampfa'
require_relative 'config/config_bot_garden'
require_relative 'config/config_cine_files'
require_relative 'config/config_core'
require_relative 'config/config_pahma'
require_relative 'config/config_ucjeps'
require_relative 'logging'
require_relative 'config/web_driver_manager'
require_relative 'config/test_config'

require_relative 'pages/page'
require_relative 'pages/collection_space_pages'
require_relative 'pages/homepage'
require_relative 'pages/bampfa/bampfa_homepage'
require_relative 'pages/botgarden/bot_garden_homepage'
require_relative 'pages/cinefiles/cine_files_homepage'
require_relative 'pages/core/core_homepage'
require_relative 'pages/pahma/pahma_homepage'
require_relative 'pages/ucjeps/ucjeps_homepage'
