require_relative '../spec_helper'
require_relative 'features/pages/web_app_page'
require_relative 'features/pages/bmu_page'
require_relative 'features/pages/image_browser_page'
require_relative 'features/pages/i_reports_page'
require_relative 'features/pages/landing_page'
require_relative 'features/pages/login_page'
require_relative 'features/pages/webapp_search_page'
